-- ============================================================
-- ProfitPilot CRM - Supabase Database Setup
-- Run this entire file in the Supabase Dashboard SQL Editor
-- ============================================================

-- 1. Settings table (single row)
create table if not exists settings (
  id bigint generated by default as identity primary key,
  exchange_rate numeric not null default 83,
  profit_goal numeric not null default 200000,
  currency_view text not null default 'USD',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2. Monthly client records (per-month snapshots)
create table if not exists monthly_client_records (
  id uuid default gen_random_uuid() primary key,
  year text not null,
  month text not null,
  business_name text not null,
  contact_person text not null default '',
  onboarding_date text not null default '',
  monthly_price numeric not null default 0,
  payment_method text not null default 'Stripe',
  payment_due_day integer not null default 1,
  contract_end_date text not null default '',
  notes text not null default '',
  status text not null default 'Active',
  status_date text not null default '',
  status_note text not null default 'None',
  payment_received numeric not null default 0,
  refund_amount numeric not null default 0,
  chargeback_amount numeric not null default 0,
  is_deleted boolean not null default false,
  deleted_at timestamptz,
  deleted_reason text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_monthly_client_year_month on monthly_client_records(year, month);
create index if not exists idx_monthly_client_deleted on monthly_client_records(is_deleted);

-- 3. Add phone and email columns to monthly_client_records
alter table monthly_client_records
  add column if not exists phone text not null default '',
  add column if not exists email text not null default '';

-- 4. Expenses table
create table if not exists expenses (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  amount numeric not null default 0,
  category text not null default '',
  frequency text not null default '',
  date text not null default '',
  status text not null default 'Paid',
  month text not null,
  year text not null,
  carried_over boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Add carried_over column if missing (for existing databases)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'expenses' and column_name = 'carried_over') then
    alter table expenses add column carried_over boolean not null default false;
  end if;
end
$$;

-- Add notes column if missing
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'expenses' and column_name = 'notes') then
    alter table expenses add column notes text not null default '';
  end if;
end
$$;

create index if not exists idx_expenses_month_year on expenses(month, year);

-- 5. Team members table
create table if not exists team_members (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  team text not null default '',
  role text not null default '',
  monthly_salary numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 6. Sync logs table
create table if not exists sync_logs (
  id uuid default gen_random_uuid() primary key,
  type text not null default '',
  message text not null default '',
  status text not null default '',
  created_at timestamptz not null default now()
);

-- 7. Insert default settings row (if not exists)
insert into settings (exchange_rate, profit_goal, currency_view)
select 83, 200000, 'USD'
where not exists (select 1 from settings);

-- ============================================================
-- USER ROLES TABLE & AUTH
-- ============================================================

-- 8. Create user_roles table
create table if not exists user_roles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null check (role = 'admin' or role = 'hr_editor' or role ~ '^pm[0-9]*_editor$'),
  created_at timestamptz default now()
);

-- Enable RLS
alter table user_roles enable row level security;

-- 9. Function to check if a user has admin role (used in policies)
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = 'public'
as $$
  select exists (
    select 1 from public.user_roles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- 10. RLS Policies for user_roles

-- Users can select their own row
drop policy if exists "users_select_own" on user_roles;
create policy "users_select_own"
  on user_roles
  for select
  to authenticated
  using (id = auth.uid());

-- Admins can select all rows
drop policy if exists "admins_select_all" on user_roles;
create policy "admins_select_all"
  on user_roles
  for select
  to authenticated
  using (public.is_admin());

-- Admins can insert rows
drop policy if exists "admins_insert" on user_roles;
create policy "admins_insert"
  on user_roles
  for insert
  to authenticated
  with check (public.is_admin());

-- Admins can update rows
drop policy if exists "admins_update" on user_roles;
create policy "admins_update"
  on user_roles
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- Admins can delete rows
drop policy if exists "admins_delete" on user_roles;
create policy "admins_delete"
  on user_roles
  for delete
  to authenticated
  using (public.is_admin());

-- ============================================================
-- CREATE USER ROLE FUNCTION (self-registration helper)
-- ============================================================

create or replace function public.create_user_role(
  p_user_id uuid,
  p_email text,
  p_role text
)
returns void
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_user_count bigint;
  v_current_uid uuid;
  v_is_admin boolean;
begin
  select count(*) into v_user_count from public.user_roles;

  if v_user_count = 0 then
    insert into public.user_roles (id, email, role)
    values (p_user_id, p_email, p_role);
    return;
  end if;

  v_current_uid := auth.uid();

  if p_role = 'admin' then
    if v_current_uid is null then
      raise exception 'You must be signed in to create an admin account.';
    end if;

    select exists (
      select 1 from public.user_roles where id = v_current_uid and role = 'admin'
    ) into v_is_admin;

    if not v_is_admin then
      raise exception 'Only existing admins can create new admin accounts.';
    end if;
  end if;

  insert into public.user_roles (id, email, role)
  values (p_user_id, p_email, p_role);
end;
$$;

-- Grant execute permission for the API
grant execute on function public.create_user_role to anon, authenticated;
grant execute on function public.is_admin to anon, authenticated;

-- ============================================================
-- AUTO-CREATE USER ROLE ON SIGNUP (trigger)
-- Fires inside the same transaction as auth.users insert,
-- so the FK constraint is always satisfied.
-- ============================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_count bigint;
  v_role text;
begin
  -- Read the role passed from frontend signUp options.data
  v_role := new.raw_app_meta_data ->> 'role';

  -- Default to pm_editor if invalid or missing
  if v_role is null or (v_role not in ('admin', 'hr_editor') and v_role !~ '^pm[0-9]*_editor$') then
    v_role := 'pm_editor';
  end if;

  select count(*) into v_count from public.user_roles;

  if v_count = 0 then
    -- First user ever: allow any role (including admin)
    insert into public.user_roles (id, email, role)
    values (new.id, new.email, v_role);
    return new;
  end if;

  -- Subsequent users: non-admin roles allowed freely
  if v_role = 'admin' then
    -- Only existing admins can create new admins
    if not exists (
      select 1 from public.user_roles
      where id = auth.uid() and role = 'admin'
    ) then
      v_role := 'pm_editor';
    end if;
  end if;

  insert into public.user_roles (id, email, role)
  values (new.id, new.email, v_role);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

-- ============================================================
-- BACKFILL: assign roles to existing users (pre-trigger)
-- First user (by created_at) becomes admin, others become pm_editor
-- ============================================================
insert into public.user_roles (id, email, role)
select
  u.id,
  u.email,
  case
    when row_number() over (order by u.created_at) = 1 then 'admin'
    else 'pm_editor'
  end as role
from auth.users u
where not exists (
  select 1 from public.user_roles r where r.id = u.id
);

-- ============================================================
-- CLIENT-TO-PM ASSIGNMENTS (admin-only feature)
-- ============================================================

create table if not exists client_pm_assignments (
  id uuid default gen_random_uuid() primary key,
  business_name text not null,
  assigned_pm text not null,
  created_at timestamptz default now(),
  unique(business_name, assigned_pm)
);

alter table client_pm_assignments enable row level security;

drop policy if exists "admins_all" on client_pm_assignments;
create policy "admins_all"
  on client_pm_assignments
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "pm_read_assigned" on client_pm_assignments;
create policy "pm_read_assigned"
  on client_pm_assignments
  for select
  to authenticated
  using (
    exists (
      select 1 from public.user_roles
      where id = auth.uid() and role = assigned_pm
    )
  );

-- ============================================================
-- 8. Audit logs table
-- ============================================================
create table if not exists audit_logs (
  id uuid default gen_random_uuid() primary key,
  user_id uuid not null,
  user_email text not null default '',
  action_type text not null,
  entity_type text not null default '',
  entity_id text not null default '',
  entity_name text not null default '',
  details jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table audit_logs enable row level security;

drop policy if exists "admin_all_audit" on audit_logs;
create policy "admin_all_audit"
  on audit_logs
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "authenticated_insert_audit" on audit_logs;
create policy "authenticated_insert_audit"
  on audit_logs
  for insert
  to authenticated
  with check (auth.uid() = user_id);
