-- Settings table (single row)
create table settings (
  id bigint generated by default as identity primary key,
  exchange_rate numeric not null default 83,
  profit_goal numeric not null default 200000,
  currency_view text not null default 'USD',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Monthly client records (per-month snapshots)
create table monthly_client_records (
  id uuid default gen_random_uuid() primary key,
  year text not null,
  month text not null,
  business_name text not null,
  contact_person text not null default '',
  onboarding_date text not null default '',
  monthly_price numeric not null default 0,
  payment_method text not null default 'Stripe',
  payment_due_day integer not null default 1,
  contract_end_date text not null default '',
  notes text not null default '',
  status text not null default 'Active',
  status_date text not null default '',
  status_note text not null default 'None',
  payment_received numeric not null default 0,
  refund_amount numeric not null default 0,
  chargeback_amount numeric not null default 0,
  is_deleted boolean not null default false,
  deleted_at timestamptz,
  deleted_reason text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_monthly_client_year_month on monthly_client_records(year, month);
create index idx_monthly_client_deleted on monthly_client_records(is_deleted);

-- Expenses table
create table expenses (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  amount numeric not null default 0,
  category text not null default '',
  frequency text not null default '',
  date text not null default '',
  status text not null default 'Paid',
  month text not null,
  year text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_expenses_month_year on expenses(month, year);

-- Team members table
create table team_members (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  team text not null default '',
  role text not null default '',
  monthly_salary numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Sync logs table
create table sync_logs (
  id uuid default gen_random_uuid() primary key,
  type text not null default '',
  message text not null default '',
  status text not null default '',
  created_at timestamptz not null default now()
);

-- Insert default settings row
insert into settings (exchange_rate, profit_goal, currency_view)
values (83, 200000, 'USD');
